### ISSUE TITLE
Tech Stack

### ISSUE THREAD

**Issue by vishnu667** [donorcall01/DonorOnCall_Server#1]
Hoping to use this thread for discussions on the tech stack and requirements.

**Comment by asifalix** [comment]
Tech stack -

Backend is in JAVA. But we're open to other as the server is early.

Android based client

DB can be MySQL for ease of use

**Comment by vishnu667** [comment]
Java and Scala mixin project using maven.

**Comment by vishnu667** [comment]
Java and Scala mixin project using maven.

if others agree with this,I will create a pull request from the following branch
https://github.com/vishnu667/DonorOnCall_Server/tree/issue-1

Other libraries which i have added to the pom structure are

Scala -> [scala 2.11.7](http://www.scala-lang.org/download/2.11.7.html)
Rest layer -> [Undertow.io](http://undertow.io)
Logging -> [slf4j](http://mvnrepository.com/artifact/org.slf4j/slf4j-log4j12/1.7.13)
Configurations -> [typesafe Config](http://mvnrepository.com/artifact/com.typesafe/config/1.3.0)
MySql Connector -> [mysql-connector-java](http://mvnrepository.com/artifact/mysql/mysql-connector-java/5.1.38)
