### ISSUE TITLE
Register as a Donor or Recipient or both

### ISSUE THREAD

**Issue by asifalix** [donorcall01/DonorOnCall_Server#2]
User should be able to register as a donor, recipient or both.

**Comment by asifalix** [comment]
Mockups at https://marvelapp.com/8436ee#8417157

**Comment by abdulmuq** [comment]
Registration requires a simple e-mail or sms verification

**Comment by pontiyaraja** [comment]
I have used Simple email now, I need e-mail from address and subject and body text.

**Comment by vishnu667** [comment]
@pontiyaraja we were wondering if you could follow the thread before you commit 
https://github.com/donorcall01/DonorOnCall_Server/issues/1.
We have a different plan for the tech stack hoping you could also join the discussion.
