### ISSUE TITLE
Users can login to the app

### ISSUE THREAD

**Issue by asifalix** [donorcall01/DonorOnCall_Server#4]
Perhaps use OATH?

https://marvelapp.com/8436ee#8417157

**Comment by vishnu667** [comment]
[Login Api Wiki](https://github.com/donorcall01/DonorOnCall_Server/wiki/Working-Api's#login) Currently its just an internal Login Api.
I've created https://github.com/donorcall01/DonorOnCall_Server/issues/28  issue, to track OAuth Support.
