### ISSUE TITLE
Users can request for blood on a map based interface

### ISSUE THREAD

**Issue by asifalix** [donorcall01/DonorOnCall_Server#5]
https://marvelapp.com/8436ee#8417157

**Comment by abdulmuq** [comment]
The Admin needs to verify and confirm the blood request before the donor information is made available

**Comment by vishnu667** [comment]
API WIKI - [Register for Blood Request](https://github.com/donorcall01/DonorOnCall_Server/wiki/Working-Api's#register-new-blood-request)

**Comment by vishnu667** [comment]
#30
